language: node_js
cache: yarn
node_js:
  - "8"
script: yarn build
env:
  global:
    - API_URL: https://ec2-34-217-177-149.us-west-2.compute.amazonaws.com/api/v1
    - BASE_URL: /react-watchlist
    - GOOGLE_CLIENT_ID: 539505879160-povfotva76gcajj42bbfg7bva763htbh.apps.googleusercontent.com
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
